// <auto-generated />
namespace DemoSignalRChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Addavatarforuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addavatarforuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201402260946522_Add-avatar-for-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
