// <auto-generated />
namespace DemoSignalRChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changeprimatykeytablenewfeeds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeprimatykeytablenewfeeds));
        
        string IMigrationMetadata.Id
        {
            get { return "201404161021079_change-primaty-key-table-newfeeds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
