// <auto-generated />
namespace DemoSignalRChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addtablecity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablecity));
        
        string IMigrationMetadata.Id
        {
            get { return "201405100306091_add-table-city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
