// <auto-generated />
namespace DemoSignalRChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addattributeRequiredtofielduserIdofclassStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addattributeRequiredtofielduserIdofclassStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201402080838385_add-attribute-Required-to-field-userId-of-class-Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
